{"schemaUrl":"https://opentelemetry.io/schemas/1.6.1","resource":{"attributes":{"k8s.namespace.name":"ic","k8s.pod.name":"dev-app-api-abcd12345-12345","com.splunk.sourcetype":"kube:container:app-service","com.splunk.source":"/var/log/pods/dev-app-api-abcd12345-efghi_jkl6789-1234-1234-1234-abcd12345/linkerd-proxy/0.log","k8s.pod.uid":"a9ff616f-3917-4960-8c5e-6c9a7e3d63df","k8s.container.restart_count":"0","k8s.container.name":"app-service","k8s.node.name":"ip-127-0-0-1","k8s.pod.labels.app":"dev-app-api","container.image.name":"ab.c5a.io/app/service","container.image.tag":"stable-1.0.0","container.id":"6b475df40f024e12b92f5a3e2f3f2b816b475df40f024e12b92f5a3e2f3f2b81","host.name":"ip-127-0-0-1","os.type":"linux","k8s.cluster.name":"dev1","deployment.environment":"production"},"droppedAttributesCount":0},"scopeLog":{"schemaUrl":"","scope":{"name":"","version":"","droppedAttributesCount":0,"attributes":{}},"logRecord":{"spanId":"","traceId":"","severityText":"","severityNumber":"SEVERITY_NUMBER_UNSPECIFIED","flags":0,"droppedAttributesCount":0,"body":"[  3097.455065s]  INFO ThreadId(01) outbound: app_core::serve: Connection closed error=connect timed out after 10s client.addr=127.0.0.1:5591 server.addr=127.0.0.254:1102","attributes":{"log.iostream":"stdout","logtag":"F"},"observedTimeUnix":{"millis":1722348201345,"nanos":142841},"timeUnix":{"millis":1722348201344,"nanos":979881}}}}